name = "Changeling Guild Cobblepack"
author = "genderneutralnoun"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4f4c43d42a91e35a10321897caa2f04bb6321c393493aa987d66dd14f43a9d5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
datapack-folder = "config/paxi/datapacks"
