name = "Changeling Guild Cobblepack"
author = "genderneutralnoun"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "244d6dc0a8c39f27566b9ffb44f0c685a327c6578dadb0106d1f15ac8d560c06"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "config/paxi/datapacks"
