name = "Changeling Guild Cobblepack"
author = "genderneutralnoun"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa5e28ba6f78389a06eb31dbd4bc24a2e89a5c6358a4e892f28da51201573048"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
datapack-folder = "config/paxi/datapacks"
