name = "Changeling Guild Vanilla Plus"
author = "genderneutralnoun"
version = "0.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6469384a89fa0817d1e01815588d7e966d8ae9de215dcd4653423ab4edbfa7e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
