name = "Changeling Guild Vanilla Plus"
author = "genderneutralnoun"
version = "0.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3f12b8096d4f10e700608103b9a83bb6550d90c70a6be8ceb95cf4b9434f7ff"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
