name = "Changeling Guild Vanilla Plus"
author = "genderneutralnoun"
version = "0.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "924acb2e5289b15d68819392d7bb261eff1457fcd2d651057701cb10a72783a1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
