version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
fastitemframes = true
everycomp = true
mcwfences = true
farmersdelight = true
mcwroofs = true
quad-lolmsmv = true
lolmcgt = true
barteringstation = true
mcwwindows = true
easymagic = true
bambooeverything = true
mcwstairs = true
doubleslabs = true
lolmfv = true
another_furniture = true
easyanvils = true
quad-lolmcrv = true
lolmbv = true
comforts = true
diagonalwalls = true
stoneworks = true
yigd = true
quad-lolmjnv = true
mcwpaths = true
mcwbridges = true
mcwlights = true
quad-lolmbhv = true
mcwtrpdoors = true
amendments = true
psittacine = true
mcwholidays = true
handcrafted = true
nemos-woodcutter = true
lolmct = true
lolmcv = true
diagonalfences = true
treechop = true
netherchested = true
new_slab_variants = true
gravestones = true
lolmst = true
mcwdoors = true
backpacked = true
lolmcmv-aft = true
cratedelight = true
supplementaries = true
morenemoswoodcuttervariants = true
suppsquared = true
lolmlv = true
bedspreads = true
chipped = true
doggytalents = true
item-placer = true
lolmft = true
echochest = true
lolmcbv = true
trashcans = true
visualworkbench = true
lootr = true
minecraft = true
animal_feeding_trough = true
fwaystones = true
displaydelight = true
lolmlmv = true
quad-lolmbdv = true
mcwfurnitures = true
tradingpost = true
lolmcmv = true
beautify = true
waystones = true
lolmgv = true
monolib = true
diagonalwindows = true
lolmblv = true
enchantinginfuser = true
rechiseled = true
adorn = true
