# Don't change this! Version used to track needed updates.
version = 1
slotMode = "DEFAULT_SLOT"
hideDebugInfoInSurvival = false
cancelElytraFlyingInLiquid = true

[accessorySettings]
clockAccessory = true
compassAccessory = true
recoveryCompassAccessory = true
calendarAccessory = true
elytraAccessory = true
spyglassAccessory = true
lanternAccessory = false
totemOfUndyingAccessory = true
enderChestAccessory = true
shulkerBoxAccessory = true
arrowAccessory = true

[infoOverlaySettings]
showYCoordinate = false
obfuscateCompassIfNotOverworld = false
obfuscateClockIfNotOverworld = true
useObfuscationEffect = false

[infoOverlaySettings.overlayFields]
coordinates = false
direction = false
biome = false
dayAndTime = false
weather = false
moonPhase = false
season = false
lastDeathLocation = false