enableHDR = true
uiBrightness = -1.0
customGamePaperWhiteBrightness = -1.0
customGamePeakBrightness = 1000.0
customGameMinimumBrightness = 0.0
customEotfEmulate = 0.0
behaviorOnVanillaScreenshotCalled = "ONLY_VANILLA"
behaviorOnVanillaF2 = "ONLY_VANILLA"
enableReplayHDRVideoExport = true
replayRecommendedCommandline = "-color_primaries bt2020 -color_trc smpte2084 -color_range pc -y -f rawvideo -pix_fmt bgra64 -s %WIDTH%x%HEIGHT% -r %FPS% -i - %FILTERS%-an -colorspace bt2020nc -color_primaries bt2020 -color_trc smpte2084 -color_range pc -c:v libx265 -b:v %BITRATE% -pix_fmt yuv420p10le \\\"%FILENAME%\\\""
replayUIBrightness = 203.0
replayGamePaperWhiteBrightness = 203.0
replayGamePeakBrightness = 10000.0
replayGameMinimumBrightness = 0.0
enableCharCallbackReplacement = true
enableIMBlockerSetStateIntegration = true
enableIMBlockerSetEnglishStateIntegration = true
enableIMBlockerSetPreeditOverlayPositionIntegration = true
enableIMBlockerSetPreeditCallbackIntegration = true
PreeditOverlayPositionFollowMonitorScale = true
useUNORMWindowPixelFormat = true
forceActivateGlDxInterop = false
autoSetPrimaries = true
customPrimaries = "SRGB"
autoSetTransferFunction = true
customTransferFunction = "SRGB"
forceDisableGlfwWorkaround = false
forceDisableBlitShaderReplacement = false
