version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
fastitemframes = true
everycomp = true
farmersdelight = true
create_new_age = true
cookingforblockheads = true
excavated_variants = true
someassemblyrequired = true
croptopia = true
mega_showdown = true
galosphere = true
silentgear = true
mcwstairs = true
redstonepen = true
clayworks = true
easyanvils = true
copycats = true
refurbished_furniture = true
large_meals = true
stonezone = true
pamhc2crops = true
lab_11_mods_unified = true
dramaticdoors = true
comforts = true
fishermens_trap = true
yigd = true
mcwbridges = true
mynethersdelight = true
tmtceic = true
handcrafted = true
ftbquests = true
functionalstorage = true
cobblemon = true
biomesoplenty = true
dndesires = true
compatdelight = true
wilderflowers = true
chiselsandbits = true
supplementaries = true
dynamictreesplus = true
culturaldelights = true
minersdelight = true
ldlib2 = true
create = true
plonk = true
silentgems = true
dtphc2 = true
create_ironworks = true
fertiliserforblockheads = true
createmetalwork = true
visualworkbench = true
minecraft = true
paraglider = true
many_more_ores_and_crafts = true
rusticdelight = true
dtbop = true
create_connected = true
refinedstorage = true
mcwfurnitures = true
createaddition = true
sophisticatedstorage = true
aquaculturedelight = true
sliceanddice = true
waystones = true
animal_pen = true
tradingpost = true
immersiveengineering = true
createnuclear = true
legendarymonuments = true
expandeddelight = true
nfm = true
createfood = true
mcwroofs = true
barteringstation = true
cobblefurnies = true
oceansdelight = true
more_immersive_wires = true
puddleflood = true
brewinandchewin = true
storagedelight = true
easymagic = true
contact = true
carved_wood = true
quark = true
another_furniture = true
doubleslabs = true
minopp = true
diagonalwalls = true
ends_delight = true
createdieselgenerators = true
farmingforblockheads = true
create_enchantment_industry = true
dtcroptopia = true
escalated = true
bellsandwhistles = true
botanypots = true
createcobblestone = true
plentyplates = true
psittacine = true
diagonalfences = true
moonlight = true
sophisticatedbackpacks = true
gemsrealm = true
netherchested = true
workshop_for_handsome_adventurer = true
tmted = true
create_klinks_n_klangs = true
cratedelight = true
create_factory = true
little_big_redstone = true
suppsquared = true
bedspreads = true
chipped = true
aquaculture = true
createcasing = true
dynamictrees = true
interiors = true
choppersdelight = true
dtaddon_lib = true
rainbowsheep = true
displaydelight = true
bibliocraft = true
create_dragons_plus = true
lootr = true
elevatorid = true
lootrmon = true
cfm = true
pamhc2trees = true
diagonalwindows = true
computercraft = true
cratedelightcroptopia = true
barbequesdelight = true
netherdepthsupgrade = true
pizzadelight = true
dtcobblemon = true
enchantinginfuser = true
serene_shrubbery = true
